import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!;

export const supabase = createClient(supabaseUrl, supabaseKey);

// ─── Database row types (snake_case từ Supabase) ───────────

export interface ProfileRow {
  id: string;
  user_id: string;
  name: string;
  avatar_color: string;
  initial: string;
  created_at: string;
  email?: string | null;
}

export interface TransactionRow {
  id: string;
  profile_id: string;
  type: 'income' | 'expense';
  title: string;
  amount: number;
  source: string;
  category: string;
  note: string;
  date: string;
  created_at: string;
  is_auto_generated?: boolean;
  linked_shared_expense_id?: string | null;
  auto_kind?: 'split_income' | 'split_expense' | null;
  excluded_from_reports?: boolean;
}

export interface CustomSourceRow {
  id: string;
  profile_id: string;
  label: string;
  icon: string;
  created_at: string;
}

export interface CustomCategoryRow {
  id: string;
  profile_id: string;
  label: string;
  icon: string;
  created_at: string;
}

export interface SharedExpenseRow {
  id: string;
  owner_user_id: string;
  owner_profile_id: string;
  owner_name: string;
  participant_type: 'linked' | 'unlinked';
  participant_user_id: string | null;
  participant_profile_id: string | null;
  participant_name: string;
  participant_email: string | null;
  direction: 'forward' | 'reverse';
  total_expense: number;
  split_amount: number;
  remaining_amount: number;
  source_transaction_id: string | null;
  status: 'pending' | 'active' | 'pending_confirm' | 'settled' | 'rejected' | 'cancelled';
  note: string;
  category: string;
  due_date: string | null;
  reject_reason: string | null;
  created_at: string;
  accepted_at: string | null;
  settled_at: string | null;
  manually_settled: boolean;
}

export interface SharedExpensePaymentRow {
  id: string;
  shared_expense_id: string;
  amount: number;
  payment_source: string | null;
  paid_at: string;
  confirmed_at: string | null;
  note: string;
  income_transaction_id: string | null;
  expense_transaction_id: string | null;
}

export interface SharedExpenseNotificationRow {
  id: string;
  recipient_user_id: string;
  type: string;
  shared_expense_id: string | null;
  actor_name: string;
  amount: number;
  message: string;
  is_read: boolean;
  created_at: string;
}

export interface SharedExpenseContactRow {
  id: string;
  owner_user_id: string;
  contact_user_id: string | null;
  contact_name: string;
  contact_email: string | null;
  contact_type: 'linked' | 'unlinked';
  last_used_at: string;
  created_at: string;
}

// ─── Mapper helpers ────────────────────────────────────────

import {
  UserProfile, Transaction, CustomSource, CustomCategory,
  SharedExpense, SharedExpensePayment, SharedExpenseNotification, SharedExpenseContact, SharedExpenseNotificationType,
} from './types';

export function toProfile(row: ProfileRow): UserProfile {
  return {
    id: row.id,
    name: row.name,
    avatarColor: row.avatar_color,
    initial: row.initial,
    createdAt: row.created_at,
    email: row.email ?? null,
  };
}

export function toTransaction(row: TransactionRow): Transaction {
  return {
    id: row.id,
    type: row.type,
    title: row.title,
    amount: row.amount,
    source: row.source,
    category: row.category,
    note: row.note,
    date: row.date,
    createdAt: row.created_at,
    isAutoGenerated: row.is_auto_generated ?? false,
    linkedSharedExpenseId: row.linked_shared_expense_id ?? null,
    autoKind: row.auto_kind ?? null,
    excludedFromReports: row.excluded_from_reports ?? false,
  };
}

export function toCustomSource(row: CustomSourceRow): CustomSource {
  return { id: row.id, label: row.label, icon: row.icon, createdAt: row.created_at };
}

export function toCustomCategory(row: CustomCategoryRow): CustomCategory {
  return { id: row.id, label: row.label, icon: row.icon, createdAt: row.created_at };
}

export function toSharedExpense(row: SharedExpenseRow, payments: SharedExpensePaymentRow[] = []): SharedExpense {
  return {
    id: row.id,
    ownerUserId: row.owner_user_id,
    ownerProfileId: row.owner_profile_id,
    ownerName: row.owner_name,
    participantType: row.participant_type,
    participantUserId: row.participant_user_id,
    participantProfileId: row.participant_profile_id,
    participantName: row.participant_name,
    participantEmail: row.participant_email,
    direction: row.direction,
    totalExpense: row.total_expense,
    splitAmount: row.split_amount,
    remainingAmount: row.remaining_amount,
    sourceTransactionId: row.source_transaction_id,
    status: row.status,
    note: row.note,
    category: row.category,
    dueDate: row.due_date,
    rejectReason: row.reject_reason,
    createdAt: row.created_at,
    acceptedAt: row.accepted_at,
    settledAt: row.settled_at,
    manuallySettled: row.manually_settled,
    payments: payments.map(toSharedExpensePayment),
  };
}

export function toSharedExpensePayment(row: SharedExpensePaymentRow): SharedExpensePayment {
  return {
    id: row.id,
    sharedExpenseId: row.shared_expense_id,
    amount: row.amount,
    paymentSource: row.payment_source,
    paidAt: row.paid_at,
    confirmedAt: row.confirmed_at,
    note: row.note,
    incomeTransactionId: row.income_transaction_id,
    expenseTransactionId: row.expense_transaction_id,
  };
}

export function toSharedExpenseNotification(row: SharedExpenseNotificationRow): SharedExpenseNotification {
  return {
    id: row.id,
    recipientUserId: row.recipient_user_id,
    type: row.type as SharedExpenseNotificationType,
    sharedExpenseId: row.shared_expense_id,
    actorName: row.actor_name,
    amount: row.amount,
    message: row.message,
    isRead: row.is_read,
    createdAt: row.created_at,
  };
}

export function toSharedExpenseContact(row: SharedExpenseContactRow): SharedExpenseContact {
  return {
    id: row.id,
    contactUserId: row.contact_user_id,
    contactName: row.contact_name,
    contactEmail: row.contact_email,
    contactType: row.contact_type,
    lastUsedAt: row.last_used_at,
  };
}
