export interface UserProfile {
  id: string;
  name: string;
  avatarColor: string;
  initial: string;
  createdAt: string;
  email?: string | null;
}

export type TransactionSource = string;
export type TransactionCategory = string;

export interface CustomSource {
  id: string;
  label: string;
  icon: string;
  createdAt: string;
}

export interface CustomCategory {
  id: string;
  label: string;
  icon: string;
  createdAt: string;
}
export type TransactionType = 'income' | 'expense';
export type AutoTxKind = 'debt_income' | 'debt_expense';

export interface Transaction {
  id: string;
  type: TransactionType;
  title: string;
  amount: number;
  source: TransactionSource;
  category: TransactionCategory;
  note: string;
  date: string;
  createdAt: string;
  isAutoGenerated?: boolean;
  linkedDebtId?: string | null;
  autoKind?: AutoTxKind | null;
}

// ─── Shared Debts (multi-tenant) ───────────────────────────

export type SharedDebtStatus =
  | 'pending'           // Chờ B accept (chỉ linked)
  | 'active'            // B đã accept, nợ đang mở
  | 'pending_confirm'   // B đã bấm "đã trả", chờ A confirm
  | 'settled'           // Đã thanh toán xong
  | 'rejected'          // B từ chối
  | 'cancelled';        // A huỷ trước khi B accept

export type DebtorType = 'linked' | 'unlinked';
export type SharedDebtDirection = 'forward' | 'reverse';

export interface SharedDebt {
  id: string;

  creditorUserId: string;
  creditorProfileId: string;
  creditorName: string;

  debtorType: DebtorType;
  debtorUserId: string | null;
  debtorProfileId: string | null;
  debtorName: string;
  debtorEmail: string | null;

  direction: SharedDebtDirection;

  totalExpense: number;
  debtAmount: number;
  remainingAmount: number;

  sourceTransactionId: string | null;

  status: SharedDebtStatus;

  note: string;
  category: string;
  dueDate: string | null;
  rejectReason: string | null;

  createdAt: string;
  acceptedAt: string | null;
  settledAt: string | null;
  manuallySettled: boolean;

  payments?: SharedDebtPayment[];
}

export interface SharedDebtPayment {
  id: string;
  sharedDebtId: string;
  amount: number;
  paymentSource: string | null;
  paidAt: string;
  confirmedAt: string | null;
  note: string;
  incomeTransactionId: string | null;
  expenseTransactionId: string | null;
}

export type DebtNotificationType =
  | 'debt_request'
  | 'debt_accepted'
  | 'debt_rejected'
  | 'payment_claimed'
  | 'payment_confirmed'
  | 'payment_denied'
  | 'debt_cancelled'
  | 'due_reminder';

export interface DebtNotification {
  id: string;
  recipientUserId: string;
  type: DebtNotificationType;
  sharedDebtId: string | null;
  actorName: string;
  amount: number;
  message: string;
  isRead: boolean;
  createdAt: string;
}

export interface DebtContact {
  id: string;
  contactUserId: string | null;
  contactName: string;
  contactEmail: string | null;
  contactType: DebtorType;
  lastUsedAt: string;
}

export interface UserSearchResult {
  userId: string;
  profileId: string;
  name: string;
  email: string | null;
  avatarColor: string;
  initial: string;
}
