export interface UserProfile {
  id: string;
  name: string;
  avatarColor: string;
  initial: string;
  createdAt: string;
  email?: string | null;
}

export type TransactionSource = string;
export type TransactionCategory = string;

export interface CustomSource {
  id: string;
  label: string;
  icon: string;
  createdAt: string;
}

export interface CustomCategory {
  id: string;
  label: string;
  icon: string;
  createdAt: string;
}
export type TransactionType = 'income' | 'expense';
export type AutoTxKind = 'split_income' | 'split_expense';

export interface Transaction {
  id: string;
  type: TransactionType;
  title: string;
  amount: number;
  source: TransactionSource;
  category: TransactionCategory;
  note: string;
  date: string;
  createdAt: string;
  isAutoGenerated?: boolean;
  linkedSharedExpenseId?: string | null;
  autoKind?: AutoTxKind | null;
  excludedFromReports?: boolean;
}

// ─── Shared Expenses ("Chi chung" / "Chia chi phí", multi-tenant) ──

export type SharedExpenseStatus =
  | 'pending'           // Chờ người cùng chia xác nhận (chỉ linked)
  | 'active'            // Đã xác nhận, đang mở
  | 'pending_confirm'   // Đã báo "đã trả", chờ người tạo xác nhận
  | 'settled'           // Đã thanh toán xong
  | 'rejected'          // Bị từ chối
  | 'cancelled';        // Huỷ trước khi được xác nhận

/** Status nào được coi là khoản chi chung "có thực" — đã được xác nhận
 *  hoặc đã/đang thanh toán. Dùng để lọc khi đưa vào dashboard/lịch. */
export const CONFIRMED_SHARED_EXPENSE_STATUSES: SharedExpenseStatus[] = ['active', 'pending_confirm', 'settled'];

export function isConfirmedSharedExpense(status: SharedExpenseStatus): boolean {
  return CONFIRMED_SHARED_EXPENSE_STATUSES.includes(status);
}

export type ParticipantType = 'linked' | 'unlinked';
export type SharedExpenseDirection = 'forward' | 'reverse';

export interface SharedExpense {
  id: string;

  ownerUserId: string;
  ownerProfileId: string;
  ownerName: string;

  participantType: ParticipantType;
  participantUserId: string | null;
  participantProfileId: string | null;
  participantName: string;
  participantEmail: string | null;

  direction: SharedExpenseDirection;

  totalExpense: number;
  splitAmount: number;
  remainingAmount: number;

  sourceTransactionId: string | null;

  status: SharedExpenseStatus;

  note: string;
  category: string;
  dueDate: string | null;
  rejectReason: string | null;

  createdAt: string;
  acceptedAt: string | null;
  settledAt: string | null;
  manuallySettled: boolean;

  payments?: SharedExpensePayment[];
}

export interface SharedExpensePayment {
  id: string;
  sharedExpenseId: string;
  amount: number;
  paymentSource: string | null;
  paidAt: string;
  confirmedAt: string | null;
  note: string;
  incomeTransactionId: string | null;
  expenseTransactionId: string | null;
}

export type SharedExpenseNotificationType =
  | 'split_request'
  | 'split_accepted'
  | 'split_rejected'
  | 'payment_claimed'
  | 'payment_confirmed'
  | 'payment_denied'
  | 'split_cancelled'
  | 'due_reminder';

export interface SharedExpenseNotification {
  id: string;
  recipientUserId: string;
  type: SharedExpenseNotificationType;
  sharedExpenseId: string | null;
  actorName: string;
  amount: number;
  message: string;
  isRead: boolean;
  createdAt: string;
}

export interface SharedExpenseContact {
  id: string;
  contactUserId: string | null;
  contactName: string;
  contactEmail: string | null;
  contactType: ParticipantType;
  lastUsedAt: string;
}

export interface UserSearchResult {
  userId: string;
  profileId: string;
  name: string;
  email: string | null;
  avatarColor: string;
  initial: string;
}
